version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

  flask_front:
    build:
      context: .
      dockerfile: ./gunicorn_flask/Dockerfile

  fastapi:
    build:
      context: .
      dockerfile: ./uvicorn_fastapi/Dockerfile

  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile

  celery:
    build:
      context: .
      dockerfile: ./app/packages/celery_client_and_worker/celery_worker.Dockerfile
