version: '3.9'

services:
  nginx:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-nginx_$GIT_COMMIT
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - fastapi
      - flask_front
    networks:
      - app-network
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - /etc/ssl/dhparam/dhparam.pem:/etc/ssl/dhparam/dhparam.pem
      - static_volume:/home/dummy-operator/flask/staticfiles

  flask_front:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-flask_front_$GIT_COMMIT
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8001 flask_app.manage:app
    expose:
      - 8001
    environment:
      - SCOPE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_PORT
      - POSTGRES_HOST
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      - TEST_USER_PWD
      - SECRET_KEY
      - BETTERSTACK_SOURCE_TOKEN
      - HCAPTCHA_SITE_KEY
      - HCAPTCHA_SITE_SECRET
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    networks:
      - app-network
    depends_on:
      - fastapi
    volumes:
      - static_volume:/home/dummy-operator/flask/staticfiles

  fastapi:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-fastapi_$GIT_COMMIT
    container_name: fastapi
    expose:
      - 8000
    environment:
      - SCOPE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_PORT
      - POSTGRES_HOST
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      - TEST_USER_PWD
      - SECRET_KEY
      - BETTERSTACK_SOURCE_TOKEN
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_PORT
      - POSTGRES_HOST
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      - ADMIN_EMAIL
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path /var/www/html --email $ADMIN_EMAIL --agree-tos --no-eff-email --force-renewal -d dummy-ops.dev -d www.dummy-ops.dev
    networks:
      - app-network

  redis:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-redis_$GIT_COMMIT
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-rabbitmq_$GIT_COMMIT
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST
      - ERLANG_COOKIE_NAME
      - NODENAME=rabbit@localhost
      - RABBITMQ_DEFAULT_PERMISSIONS_REGEX=^.*$$
    expose:
      - 5672
    depends_on:
      - flask_front
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/20-custom.conf
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - app-network

  celery:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-celery_$GIT_COMMIT
    container_name: celery
    expose:
      - 5555
    environment:
      - SCOPE
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - TIMEZONE=$TIMEZONE
      - SENDGRID_API_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_PORT
      - POSTGRES_HOST
      - PDF_FOLDER_PATH
      - PDF_FILE_NAME
    volumes:
      - static_volume:/home/dummy-operator/staticfiles
    depends_on:
      - redis
      - rabbitmq
      - flask_front
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  certbot-etc:
  certbot-var:
  web-root:
  rabbitmq_data:
  redis_data:

networks:
  app-network:
    driver: bridge
