services:
  nginx:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-nginx_$GIT_COMMIT
    ports:
      - 80:80
      - 443:443
    depends_on:
      - fastapi
      - flask_front
    networks:
      - app-network
    deploy:
      replicas: 1
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - /etc/ssl/dhparam/dhparam.pem:/etc/ssl/dhparam/dhparam.pem
      - static_volume:/home/dummy-operator/flask/staticfiles
      - ./robots.txt:/usr/share/nginx/html/robots.txt
      - ./ads.txt:/usr/share/nginx/html/ads.txt

  flask_front:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-flask_front_$GIT_COMMIT
    command: gunicorn --bind 0.0.0.0:8001 flask_app.manage:app
    environment:
      - CELERY_RESULT_BACKEND
      - HCAPTCHA_SITE_KEY
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_TEST_DB_NAME
      - POSTGRES_USER
      - SCOPE
      - TEST_USER_PWD
      - MPLCONFIGDIR
    secrets:
      - ADMIN_EMAIL
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - BETTERSTACK_SOURCE_TOKEN
      - CELERY_BROKER_URL
      - HCAPTCHA_SITE_SECRET
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - SENDGRID_API_KEY
    networks:
      - app-network
    deploy:
      replicas: 1
    depends_on:
      - fastapi
    volumes:
      - static_volume:/home/dummy-operator/flask/staticfiles

  fastapi:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-fastapi_$GIT_COMMIT
    environment:
      - CELERY_RESULT_BACKEND
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_TEST_DB_NAME
      - POSTGRES_USER
      - SCOPE
      - TEST_USER_PWD
    secrets:
      - ADMIN_EMAIL
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - BETTERSTACK_SOURCE_TOKEN
      - CELERY_BROKER_URL
      - POSTGRES_PASSWORD
      - SECRET_KEY
    networks:
      - app-network
    deploy:
      replicas: 1
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_TEST_DB_NAME
      - POSTGRES_USER
      - SCOPE
    secrets:
      - ADMIN_EMAIL
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
      - POSTGRES_PASSWORD
    networks:
      - app-network
    deploy:
      replicas: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      - CERTBOT_EMAIL
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path /var/www/html --email $ADMIN_EMAIL --agree-tos --no-eff-email --force-renewal -d dummy-ops.dev -d www.dummy-ops.dev
    networks:
      - app-network
    deploy:
      replicas: 1

  redis:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-redis_$GIT_COMMIT
    volumes:
      - redis_data:/data
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network
    deploy:
      replicas: 1

  rabbitmq:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-rabbitmq_$GIT_COMMIT
    environment:
      - NODENAME
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_VHOST
      - RABBITMQ_DEFAULT_PERMISSIONS_REGEX=^.*$$
    secrets:
      - RABBITMQ_DEFAULT_PASS
    depends_on:
      - flask_front
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - app-network
    deploy:
      replicas: 1

  celery:
    image: memphistools/public_repo:dummy_fastapi_flask_blog_app-celery_$GIT_COMMIT
    environment:
      - CELERY_RESULT_BACKEND
      - PDF_FOLDER_PATH
      - PDF_FILE_NAME
      - TIMEZONE
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PRODUCTION_DB_NAME
      - POSTGRES_TEST_DB_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SCOPE
    secrets:
      - CELERY_BROKER_URL
      - SENDGRID_API_KEY
      - POSTGRES_PASSWORD
      - ADMIN_EMAIL
      - ADMIN_LOGIN
      - ADMIN_PASSWORD
    volumes:
      - static_volume:/home/dummy-operator/staticfiles
    depends_on:
      - redis
      - rabbitmq
      - flask_front
    networks:
      - app-network
    deploy:
      replicas: 2

volumes:
  postgres_data:
  static_volume:
  certbot-etc:
  certbot-var:
  web-root:
  rabbitmq_data:
  redis_data:

networks:
  app-network:
    driver: overlay

secrets:
  ADMIN_EMAIL:
    external: true
  ADMIN_LOGIN:
    external: true
  ADMIN_PASSWORD:
    external: true
  BETTERSTACK_SOURCE_TOKEN:
    external: true
  BETTERSTACK_TEAM_TOKEN:
    external: true
  CELERY_BROKER_URL:
    external: true
  HCAPTCHA_SITE_SECRET:
    external: true
  POSTGRES_PASSWORD:
    external: true
  RABBITMQ_DEFAULT_PASS:
    external: true
  SECRET_KEY:
    external: true
  SENDGRID_API_KEY:
    external: true
