services:
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - certbot-etc:/etc/letsencrypt
    environment:
      - VAULT_ADDR=https://dummy-ops.dev:8200
      - VAULT_API_ADDR=https://dummy-ops.dev:8200
    command: /bin/bash /vault/scripts/build_it_up.sh
    networks:
      - vault-network

volumes:
  certbot-etc:
  vault-data:

networks:
  vault-network:
    driver: bridge
