[pytest]
python_files = app/tests/test_* app/test_* tests.py test_*.py *_test.py
# More an example since we excluded path in the coverage report (.coveragerc)
addopts = -v --ignore=app/packages/celery_client_and_worker/
testpaths =
    app
